In [3]:
# Exercise 1

import numpy as np

arr1 = np.arange(1, 11)
reshaped_arr = arr1.reshape(2, 5)
print("Exercise 1 Output:\n", reshaped_arr)


Exercise 1 Output:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
# Exercise 2
arr2 = np.arange(1, 21)
sliced_arr = arr2[5:16]  # includes index 5 to 15
print("Exercise 2 Output:\n", sliced_arr)

Exercise 2 Output:
 [ 6  7  8  9 10 11 12 13 14 15 16]


In [7]:
# Exercise 3

import pandas as pd

fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruit_series['pears'] = 4
print("Exercise 3 Output:\n", fruit_series)


Exercise 3 Output:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [9]:
# Exercise 4

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ian', 'Jack'],
    'age': [25, 32, 28, 35, 30, 26, 40, 29, 22, 31],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}
df = pd.DataFrame(data)
print("Exercise 4 Output:\n", df)

Exercise 4 Output:
       name  age gender
0    Alice   25      F
1      Bob   32      M
2  Charlie   28      M
3    David   35      M
4      Eva   30      F
5    Frank   26      M
6    Grace   40      F
7    Helen   29      F
8      Ian   22      M
9     Jack   31      M


In [11]:
# Exercise 5
occupations = ['Programmer', 'Manager', 'Analyst', 'Manager', 'Analyst', 
               'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager']
df['occupation'] = occupations
print("Exercise 5 Output:\n", df)


Exercise 5 Output:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   28      M     Analyst
3    David   35      M     Manager
4      Eva   30      F     Analyst
5    Frank   26      M  Programmer
6    Grace   40      F     Manager
7    Helen   29      F     Analyst
8      Ian   22      M  Programmer
9     Jack   31      M     Manager


In [13]:
# Exercise 6
age_filtered = df[df['age'] >= 30]
print("Exercise 6 Output:\n", age_filtered)


Exercise 6 Output:
     name  age gender occupation
1    Bob   32      M    Manager
3  David   35      M    Manager
4    Eva   30      F    Analyst
6  Grace   40      F    Manager
9   Jack   31      M    Manager


In [15]:
# Exercise 7
df.to_csv('people_data.csv', index=False)

# Read and display the CSV
df_from_csv = pd.read_csv('people_data.csv')
print("Exercise 7 Output:\n", df_from_csv)


Exercise 7 Output:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   28      M     Analyst
3    David   35      M     Manager
4      Eva   30      F     Analyst
5    Frank   26      M  Programmer
6    Grace   40      F     Manager
7    Helen   29      F     Analyst
8      Ian   22      M  Programmer
9     Jack   31      M     Manager
